"""Finance MVP domain foundation.

F1 is deliberately isolated from LegalRAG Pro's legal analytical stack. It
contains immutable finance records, canonical identities/serialization, and
point-in-time validation only.
"""

from .identity import canonical_decimal_text, derive_finance_id
from .models import (
    COMPANY_SCHEMA_VERSION,
    FINANCIAL_FACT_SCHEMA_VERSION,
    FINANCIAL_OBSERVATION_SCHEMA_VERSION,
    FINANCIAL_PERIOD_SCHEMA_VERSION,
    FINANCE_WORKSPACE_SCHEMA_VERSION,
    SECURITY_SCHEMA_VERSION,
    Company,
    FinanceWorkspace,
    FinancialFact,
    FinancialObservation,
    FinancialPeriod,
    FinancialPeriodType,
    Security,
    SecurityType,
    WorkspaceStatus,
)
from .serialization import (
    dumps_company,
    dumps_finance_workspace,
    dumps_financial_fact,
    dumps_financial_observation,
    dumps_financial_period,
    dumps_security,
    financial_fact_identity_payload_to_dict,
    financial_observation_identity_payload_to_dict,
    financial_period_identity_payload_to_dict,
    loads_company,
    loads_finance_workspace,
    loads_financial_fact,
    loads_financial_observation,
    loads_financial_period,
    loads_security,
)
from .validation import (
    observation_available_as_of,
    observation_knowledge_available_at,
    validate_company,
    validate_finance_workspace,
    validate_financial_fact,
    validate_financial_observation,
    validate_financial_period,
    validate_security,
)

__all__ = [
    "COMPANY_SCHEMA_VERSION",
    "FINANCIAL_FACT_SCHEMA_VERSION",
    "FINANCIAL_OBSERVATION_SCHEMA_VERSION",
    "FINANCIAL_PERIOD_SCHEMA_VERSION",
    "FINANCE_WORKSPACE_SCHEMA_VERSION",
    "SECURITY_SCHEMA_VERSION",
    "Company",
    "FinanceWorkspace",
    "FinancialFact",
    "FinancialObservation",
    "FinancialPeriod",
    "FinancialPeriodType",
    "Security",
    "SecurityType",
    "WorkspaceStatus",
    "canonical_decimal_text",
    "derive_finance_id",
    "dumps_company",
    "dumps_finance_workspace",
    "dumps_financial_fact",
    "dumps_financial_observation",
    "dumps_financial_period",
    "dumps_security",
    "financial_fact_identity_payload_to_dict",
    "financial_observation_identity_payload_to_dict",
    "financial_period_identity_payload_to_dict",
    "loads_company",
    "loads_finance_workspace",
    "loads_financial_fact",
    "loads_financial_observation",
    "loads_financial_period",
    "loads_security",
    "observation_available_as_of",
    "observation_knowledge_available_at",
    "validate_company",
    "validate_finance_workspace",
    "validate_financial_fact",
    "validate_financial_observation",
    "validate_financial_period",
    "validate_security",
]
