"""Public v1 core contract for LegalRAG Pro immutable source evidence."""

from .identity import (
    canonical_json_bytes,
    canonical_uuid,
    derive_sha256_id,
    derive_source_document_instance_id,
    sha256_bytes,
    sha256_text,
    validate_sha256_hex,
    validate_sha256_id,
)
from .models import (
    BindingClass,
    BoundTextRole,
    ChunkingProfile,
    EvidenceBinding,
    ExtractionMethod,
    ExtractionProfile,
    ProjectionBindingCoverage,
    ProjectionBindingEntry,
    ProjectionEvidenceBindingManifest,
    SourceBoundAnalysisReceipt,
    SourceChunkSnapshot,
    SourceDocumentManifest,
    SourcePageSnapshot,
    VerifiedEvidenceUse,
)
from .serialization import (
    dumps_evidence_binding,
    dumps_projection_evidence_binding_manifest,
    dumps_source_bound_analysis_receipt,
    dumps_source_document_manifest,
    loads_evidence_binding,
    loads_projection_evidence_binding_manifest,
    loads_source_bound_analysis_receipt,
    loads_source_document_manifest,
)
from .validation import (
    validate_chunking_profile,
    validate_evidence_binding,
    validate_extraction_profile,
    validate_projection_evidence_binding_manifest,
    validate_source_bound_analysis_receipt,
    validate_source_document_manifest,
)

__all__ = [
    "BindingClass",
    "BoundTextRole",
    "ChunkingProfile",
    "EvidenceBinding",
    "ExtractionMethod",
    "ExtractionProfile",
    "ProjectionBindingCoverage",
    "ProjectionBindingEntry",
    "ProjectionEvidenceBindingManifest",
    "SourceBoundAnalysisReceipt",
    "SourceChunkSnapshot",
    "SourceDocumentManifest",
    "SourcePageSnapshot",
    "VerifiedEvidenceUse",
    "canonical_json_bytes",
    "canonical_uuid",
    "derive_sha256_id",
    "derive_source_document_instance_id",
    "dumps_evidence_binding",
    "dumps_projection_evidence_binding_manifest",
    "dumps_source_bound_analysis_receipt",
    "dumps_source_document_manifest",
    "loads_evidence_binding",
    "loads_projection_evidence_binding_manifest",
    "loads_source_bound_analysis_receipt",
    "loads_source_document_manifest",
    "sha256_bytes",
    "sha256_text",
    "validate_chunking_profile",
    "validate_evidence_binding",
    "validate_extraction_profile",
    "validate_projection_evidence_binding_manifest",
    "validate_sha256_hex",
    "validate_sha256_id",
    "validate_source_bound_analysis_receipt",
    "validate_source_document_manifest",
]
